export * from "./ikamah.table"
export * from "./languages.table"
export * from "./notices.table"
export * from "./prayerTime.table"
export * from "./ramadan.table"
export * from "./settings.table"
export * from "./translations.table"